Task-1-4_leap_year_check
gsa038/hello-php pull request #10
Opened 2020-05-21 18:15 UTC by gsa038

Написать программу, считывающую из стандартного ввода целое число N и
выдающую информацию, високосный ли год N.

Доработать программу, чтобы она умела считывать число из аргументов
командной строки, и в случае, если аргументы были, уже не обращалась к
стандартному вводу

2020-05-21 18:41 UTC, lugingf requested changes

2020-05-21 18:41 UTC, lugingf commented on leap_year_check.php
> +function getUserInput(string $text):string {
Вот эта функция у нас уже была) Давай вынесем ее в отдельный файл, где будем складывать всякие полезные универсальные функции и будем их переиспользовать

2020-05-21 19:52 UTC, gsa038 commented on leap_year_check.php
> +function getUserInput(string $text):string {
+ utils.php

2020-05-22 11:32 UTC, lugingf requested changes

2020-05-22 11:32 UTC, lugingf commented on leap_year_check.php
> +if ($argc == 2) {
То есть, если мы введем больше одного аргумента, скрипт скажет, что год мы ввели неверно?)

2020-05-22 11:32 UTC, lugingf commented on leap_year_check.php
> +if (strlen($year) != 4 || !ctype_digit($year)) {
А мне хочется узнать был ли 42й год високосным или нет) Или 998й

2020-05-22 11:32 UTC, lugingf commented on leap_year_check.php
> +function isLeapYear(int $year):string {
давай пробел после двоеточия тут ставить

2020-05-22 11:32 UTC, lugingf commented on leap_year_check.php
> +        return "True";
Ой, а зачем строкой то?

2020-05-22 13:01 UTC, gsa038 commented on leap_year_check.php
> +if ($argc == 2) {
Он скажет, что требуется один аргумент, но было введено больше

2020-05-22 13:01 UTC, gsa038 commented on leap_year_check.php
> +function isLeapYear(int $year):string {
+

2020-05-22 13:02 UTC, gsa038 commented on leap_year_check.php
> +if (strlen($year) != 4 || !ctype_digit($year)) {
0042, 0998, но можно нули подставлять)

2020-05-22 13:04 UTC, gsa038 commented on leap_year_check.php
> +        return "True";
Строкой, чтобы сразу в вывод без преобразований

2020-05-22 13:04 UTC, lugingf commented on leap_year_check.php
> +if (strlen($year) != 4 || !ctype_digit($year)) {
Ну... не :)

2020-05-22 13:07 UTC, gsa038 commented on leap_year_check.php
> +        return "True";
Править под bool?

2020-05-22 13:07 UTC, lugingf commented on leap_year_check.php
> +        return "True";
Не, метод назван хорошо, isЧтоНибудь(), но такие должны возвращать bool. Никаких строковых 'True'/'False'. Преобразования для вывода(отправки, запили с БД) должны быть независимо.

2020-05-22 13:08 UTC, gsa038 commented on leap_year_check.php
> +if ($argc == 2) {
Убрать эту проверку?

2020-05-22 13:08 UTC, gsa038 commented on leap_year_check.php
> +        return "True";
+

2020-05-22 13:13 UTC, gsa038 commented on leap_year_check.php
> +if (strlen($year) != 4 || !ctype_digit($year)) {
+

2020-05-22 13:13 UTC, lugingf commented on leap_year_check.php
> +if ($argc == 2) {
а, увидел

2020-05-22 13:14 UTC, gsa038 commented on leap_year_check.php
> +        return "True";
printBool вынес в utils.php

2020-05-22 13:16 UTC, gsa038 commented on leap_year_check.php
> +if ($argc == 2) {
В начало поставил, чтобы оптимальней было

2020-05-22 13:16 UTC, lugingf requested changes

2020-05-22 13:16 UTC, lugingf commented on utils.php
> +function printBool(bool $bool): string {
Не, Стас. Тут такое нам не надо. Пользователю хорошо бы писать "Високосный". И это специфично сейчас для конкретной задачи.

2020-05-22 13:22 UTC, gsa038 commented on utils.php
> +function printBool(bool $bool): string {
Поправил

2020-05-22 13:23 UTC, gsa038 commented on utils.php
> +function printBool(bool $bool): string {
убрал из utils и сделал специфичное имя

2020-05-22 18:01 UTC, lugingf requested changes

2020-05-22 18:01 UTC, lugingf commented on leap_year_check.php
> +    if ($bool == 1) {
Название для переменной такое не надо.
Не надо сравнивать bool и int значение.
Самое правильное в php сравнивать через тройное "==="

2020-05-22 18:01 UTC, lugingf commented on leap_year_check.php
> +        return true;
давай тут напишем либо 
`$result = date('L',$date);
return $result;`

либо `return date('L',$date);`

2020-05-22 18:33 UTC, gsa038 commented on leap_year_check.php
> +    if ($bool == 1) {
Да, блин что-то я тут тупанул(
Про тройное, ок
+

2020-05-22 18:33 UTC, gsa038 commented on leap_year_check.php
> +        return true;
+точно

2020-05-22 18:43 UTC, gsa038 commented on leap_year_check.php
> +        return true;
return (bool)(date('L',$date));

2020-05-22 18:44 UTC, gsa038 commented on leap_year_check.php
> +        return true;
Иначе на тип string ругается

2020-05-22 19:06 UTC, lugingf commented on leap_year_check.php
> +        return true;
Посыл в том, чтобы не делать неявных преобразований типов.

2020-05-22 19:28 UTC, gsa038 commented on leap_year_check.php
> +        return true;
return (bool)date('L',$date);
Это ж как раз явное у нас

2020-05-22 19:29 UTC, gsa038 commented on leap_year_check.php
> +        return true;
А так ясно

2020-05-22 19:30 UTC, gsa038 commented on leap_year_check.php
> +        return true;
Даже без ссылки к преобразованиям так более кратко и лаконично)

2020-05-25 16:04 UTC, lugingf requested changes

2020-05-25 16:04 UTC, lugingf commented on leap_year_check.php
> +    return (bool)date('L',$date);
А что нам date() тут отдает реально?

2020-05-25 16:04 UTC, lugingf commented on leap_year_check.php
> +    fwrite(STDERR, "Year must consist max 4 positive integer");
Ну почему же?))

2020-05-25 16:04 UTC, lugingf commented on leap_year_check.php
> +fwrite(STDOUT, printIsLeap(isLeapYear((int)$year), $year));
Давай стараться все таки избегать таких вложенностей. Это прям порой очень мешает, когда читаешь чей-то код, а там матрешка целая. Или когда ловишь ошибку, оно тебе пишет "на 25й строке" - а там пяток функций одна в другой

2020-05-26 05:34 UTC, gsa038 commented on leap_year_check.php
> +    return (bool)date('L',$date);
string(1) "1" для значения "0000-01-01"
А хочется bool получить в ответ(

2020-05-26 05:36 UTC, gsa038 commented on leap_year_check.php
> +    fwrite(STDERR, "Year must consist max 4 positive integer");
Я тут что-то не понял, вроде все норм

2020-05-26 05:38 UTC, gsa038 commented on leap_year_check.php
> +fwrite(STDOUT, printIsLeap(isLeapYear((int)$year), $year));
+ Все разложил по строкам)

2020-05-27 10:57 UTC, lugingf commented on leap_year_check.php
> +    fwrite(STDERR, "Year must consist max 4 positive integer");
Года позже 9999 мы не рассматриваем, хотя можем же(

2020-05-27 11:03 UTC, lugingf requested changes

2020-05-27 11:03 UTC, lugingf commented on leap_year_check.php
> +function printIsLeap(bool $isLeap, string $year): string
Только тут не print, а get

2020-05-27 11:03 UTC, lugingf commented on leap_year_check.php
> +function printIsLeap(bool $isLeap, string $year): string
Даже лучше getIsLeapString

2020-05-27 11:03 UTC, lugingf commented on leap_year_check.php
> +    return (bool)date('L',$date);
Давай проверим
4й год н.э. високосный?
а 27г до н.э високосный или нет? А разницу Юлианского и Григорианского календарей эта функция учитывает? :)

2020-05-27 17:52 UTC, gsa038 commented on leap_year_check.php
> +function printIsLeap(bool $isLeap, string $year): string
+

2020-05-27 19:25 UTC, gsa038 commented
+

2020-05-27 19:25 UTC, gsa038 commented on leap_year_check.php
> +    fwrite(STDERR, "Year must consist max 4 positive integer");
+

2020-05-27 19:25 UTC, gsa038 commented on leap_year_check.php
> +    return (bool)date('L',$date);
+

2020-05-28 07:12 UTC, lugingf requested changes

2020-05-28 07:12 UTC, lugingf commented on leap_year_check.php
> +function printIsLeap(bool $isLeap, string $year): string
так не print же(

2020-05-28 07:12 UTC, lugingf commented on leap_year_check.php
> +    if ($year > 12) {
Давай стараться делать поменьше отступов. Тут лучше было бы инвертнуть проверку и выполнить return false, а все тело под if'ом вынести за него

2020-05-28 07:43 UTC, gsa038 commented on leap_year_check.php
> +    if ($year > 12) {
- print совсем убрал
- инвертнул, поправил

2020-06-01 15:22 UTC, lugingf approved these changes

2020-06-01 19:30 UTC, merged