Task-1-10 from_decimal_converter
gsa038/hello-php pull request #11
Opened 2020-05-25 07:37 UTC by gsa038

Написать программу, которая принимает в качестве аргументов основание системы
счисления (число от 2 до 16) и последовательность целых десятеричных чисел,
которые переводит в соответствующую систему счисления и выводит на экран
построчно в формате "<десятеричное число> = <число в новой системе 
счисления>". Программа должна проверять аргументы на корректность. Не
использовать стандартную функцию base_convert

2020-05-25 16:32 UTC, lugingf requested changes

2020-05-25 16:32 UTC, lugingf commented on from_decimal_converter.php
> +$decimalNumbersSequence = explode("," , getUserInput("Please input a sequence of decumal number looks as 1,2,3,4,5..etc"));
Не, давай как раньше. Минимум интерактивности. Как линуксовая утилита, или api сервиса. Нам нужен ввод - мы все необходимое получаем сразу. Придумываем формат ввода, обозначаем это как контракт, и работаем с ним. Там будет одно задание с "перезапросом", но там специально будет это указано

2020-05-25 16:32 UTC, lugingf commented on from_decimal_converter.php
> +fwrite(STDOUT, "Numbers system is $numbersSystem\n");
Думаю fwrite() пора обернуть в какую-нибудь свою функцию (две), чтобы в теле основного скрипта не привязываться к тому, что это консольное приложение

2020-05-25 16:32 UTC, lugingf commented on from_decimal_converter.php
> +    do {
Мне кажется, нам тут очень не хватает какой-нибудь функции `getInNewBase(): string`
И вообще, как пишет Фаулер - если есть возможность вынести часть код в метод, и обозвать его как-нибудь, чтобы было понятно что этот метод делает, то хорошо бы так и сделать :)

2020-05-25 16:32 UTC, lugingf commented on from_decimal_converter.php
> +    while ($reminder !== 0);
Поймал себя на мысли, что ни разу нигде не видел do-while. Обычно всегда пишут через просто while().
Тут не могу сказать почему так, но просто имей ввиду

2020-05-26 05:20 UTC, gsa038 commented
> Поймал себя на мысли, что ни разу нигде не видел do-while. Обычно всегда пишут через просто while().
Тут не могу сказать почему так, но просто имей ввиду 

Поправить на while?

2020-05-27 19:41 UTC, gsa038 commented on from_decimal_converter.php
> +$decimalNumbersSequence = explode("," , getUserInput("Please input a sequence of decumal number looks as 1,2,3,4,5..etc"));
+

2020-05-27 19:42 UTC, gsa038 commented on from_decimal_converter.php
> +fwrite(STDOUT, "Numbers system is $numbersSystem\n");
вынес printInfo() и printError() в utils.php

2020-05-27 19:47 UTC, gsa038 commented on from_decimal_converter.php
> +    while ($reminder !== 0);
Поправил на while

2020-05-27 20:01 UTC, gsa038 commented on from_decimal_converter.php
> +    do {
+

2020-05-28 07:14 UTC, lugingf requested changes

2020-05-28 07:14 UTC, lugingf commented on from_decimal_converter.php
> +
Пустая строка сразу после if'a лишняя. Часто статические анализаторы или линтеры такое не пропускают

2020-05-28 07:32 UTC, gsa038 commented on from_decimal_converter.php
> +
+

2020-06-01 15:27 UTC, lugingf requested changes

2020-06-01 15:27 UTC, lugingf commented on from_decimal_converter.php
> +$decimalNumbersSequence = explode("," , getUserInput("Input a sequence of decimal numbers in format: 1,2,3,4,5..etc"));
Давай все же без двух getUserInput'ов
Мы выучили в прошлых заданиях именованные параметры - давай сделаем что-то вроде --base=10 1,2,3,4,5,6

2020-06-02 19:40 UTC, gsa038 commented on from_decimal_converter.php
> +$decimalNumbersSequence = explode("," , getUserInput("Input a sequence of decimal numbers in format: 1,2,3,4,5..etc"));
Убрал getUserInput'ы.
Добавил обязательные параметры.

2020-06-08 12:18 UTC, lugingf approved these changes

2020-06-09 17:05 UTC, merged