Task 2 1 string to array dump
gsa038/hello-php pull request #12
Opened 2020-05-27 20:08 UTC by gsa038

Написать программу, которая считывает из стандартного ввода строку вида: "a=1;
b=2; c=agfda; derp=; eee=" (в конце строки точка с запятой не обязательна, ключи и
значения могут содержать любые символы, кроме ";" и "=", значения могут быть
пустыми) и формирует массив ключ-значение, соответствующий переданной
строке. Результирующий массив вывести любой отладочной функцией.

2020-05-28 07:18 UTC, lugingf requested changes

2020-05-28 07:18 UTC, lugingf commented on print_string_to_array.php
> +    $parts = explode(';', $stringToConvert);
а что будет, если строка будет закончена символом `;` ?

2020-05-28 07:18 UTC, lugingf commented on print_string_to_array.php
> +    $parts = explode(';', $stringToConvert);
Или два раза подряд попадется точка с запятой?

2020-05-28 07:18 UTC, lugingf commented on print_string_to_array.php
> +        list($key, $value) = explode('=', $part);
А если будет два равно подряд?

2020-05-29 12:27 UTC, gsa038 commented on print_string_to_array.php
> +    $parts = explode(';', $stringToConvert);
+

2020-05-29 12:27 UTC, gsa038 commented on print_string_to_array.php
> +        list($key, $value) = explode('=', $part);
+ тогда exit()

2020-06-08 12:18 UTC, lugingf approved these changes

2020-06-09 17:06 UTC, merged