Task 2 2 arguments to dates
gsa038/hello-php pull request #14
Opened 2020-06-05 06:17 UTC by gsa038

Написать программу, которая получает аргументами список дат вида "31.12.2015" и проверяет их на корректность. По каждому аргументу вывести результат проверки - ок или нет. Учитывать число дней в месяце и високосность года.

2020-06-05 06:18 UTC, gsa038 commented
Я тут поправил скрипт из соседней таски, чтобы ты глянул. Мне кажется потом логичным, откатить его и поправить в нужной ветке и замержить, но только после одобрения

2020-06-08 12:21 UTC, lugingf requested changes

2020-06-08 12:21 UTC, lugingf commented on argv_to_dates.php
> +    $monthLengths = [31,28,31,30,31,30,31,31,30,31,30,31];
Так а если високосный год попадется?)

Вообще в PHP есть какой-то готовый метод валидации дат. Может попробуем его заиспользовать?

2020-06-08 16:24 UTC, gsa038 commented on argv_to_dates.php
> +    $monthLengths = [31,28,31,30,31,30,31,31,30,31,30,31];
Там есть проверка специальная)

2020-06-08 16:24 UTC, gsa038 commented on argv_to_dates.php
> +    $monthLengths = [31,28,31,30,31,30,31,31,30,31,30,31];
Я все предусмотрел)

2020-06-15 14:47 UTC, lugingf requested changes

2020-06-15 14:47 UTC, lugingf commented on argv_to_dates.php
> +if (basename($_SERVER['PHP_SELF']) === "argv_to_dates.php") {
А это зачем?

2020-06-15 14:47 UTC, lugingf commented on argv_to_dates.php
> +            printInfo(getIsValidDateString($date)."\n");
У нас тут опять матрешка вызовов(

2020-06-15 19:14 UTC, gsa038 commented on argv_to_dates.php
> +if (basename($_SERVER['PHP_SELF']) === "argv_to_dates.php") {
Это для переиспользования скрипта)
Могу убрать

2020-06-18 05:29 UTC, gsa038 commented on argv_to_dates.php
> +            printInfo(getIsValidDateString($date)."\n");
+

2020-06-18 05:29 UTC, gsa038 commented on argv_to_dates.php
> +if (basename($_SERVER['PHP_SELF']) === "argv_to_dates.php") {
Убрал

2020-09-03 07:09 UTC, lugingf approved these changes

2020-09-07 08:14 UTC, merged