task-1-3
gsa038/hello-php pull request #3
Opened 2020-05-19 12:33 UTC by gsa038

This script: 
- gets user age,
- calculates user_min_birth_date using current time,
- calculates diffrence between user_min_birth_date and birthday of writers

2020-05-19 12:52 UTC, lugingf requested changes
О, еще.
Давай в описании к PR писать задание. Так потом проще будет проверять)

2020-05-19 12:52 UTC, lugingf commented on compare_age.php
> +$writers_birthdays = array(
поехали по кодстайлу
у нас будет $camelCase. Переменные и функции с маленькой. Классы с большой

массивы будем объявлять по новому, через []

2020-05-19 12:52 UTC, lugingf commented on compare_age.php
> +
пустая строка лишняя

2020-05-19 12:52 UTC, lugingf commented on compare_age.php
> +intval($user_age = readline());
а что если пользователь введет не число? Давай обработаем этот кейс

2020-05-19 12:52 UTC, lugingf commented on compare_age.php
> +$user_min_birth_date = date_create(date("Y-m-d", mktime(0, 0, 0, date("m") , date("d"), date("Y") - $user_age)));
а что значит "min" в названии?

2020-05-19 12:52 UTC, lugingf commented on compare_age.php
> +$user_min_birth_date = date_create(date("Y-m-d", mktime(0, 0, 0, date("m") , date("d"), date("Y") - $user_age)));
Еще, кажется, тут переусложнено. 
Текущую дату по идее можно взять сильно проще. Ну и в рамках текущего задания нас интересует только год. 
Еще просьба не городить длинные цепочки вложенных функций. Лучше подразбить на отдельные переменные и потом с ними работать. Так потом проще читается

2020-05-19 13:09 UTC, gsa038 commented on compare_age.php
> +$user_min_birth_date = date_create(date("Y-m-d", mktime(0, 0, 0, date("m") , date("d"), date("Y") - $user_age)));
min значит, что считаем дату рождения пользователя от сегодняшнего дня, фактически он может быть старше)

2020-05-19 13:10 UTC, lugingf commented on compare_age.php
> +$user_min_birth_date = date_create(date("Y-m-d", mktime(0, 0, 0, date("m") , date("d"), date("Y") - $user_age)));
Предлагаю пока забить на даты и принять, что у нас может быть погрешность)

2020-05-19 13:12 UTC, gsa038 commented on compare_age.php
> +
+

2020-05-19 19:32 UTC, gsa038 commented on compare_age.php
> +$writers_birthdays = array(
+

2020-05-19 19:32 UTC, gsa038 commented on compare_age.php
> +intval($user_age = readline());
+

2020-05-19 19:32 UTC, gsa038 commented on compare_age.php
> +$user_min_birth_date = date_create(date("Y-m-d", mktime(0, 0, 0, date("m") , date("d"), date("Y") - $user_age)));
+

2020-05-19 19:32 UTC, gsa038 commented on compare_age.php
> +$user_min_birth_date = date_create(date("Y-m-d", mktime(0, 0, 0, date("m") , date("d"), date("Y") - $user_age)));
+

2020-05-19 19:33 UTC, gsa038 commented on compare_age.php
> +$user_min_birth_date = date_create(date("Y-m-d", mktime(0, 0, 0, date("m") , date("d"), date("Y") - $user_age)));
Сделал все попроще)

2020-05-19 21:38 UTC, lugingf requested changes
тест

2020-05-19 21:38 UTC, lugingf commented on compare_age.php
> +    while (true) {
Не, давай так не делать без необходимости. Нам по заданию нужно один раз спросить и один раз вывести. В вечный цикл это все оборачивать не стоит :)

2020-05-19 21:38 UTC, lugingf commented on compare_age.php
> +    define("MESSAGE1",  "Enter your age:");
Определить тексты через константы - это норм. Но тут define нам не нужен. Можно через конструкцию const CONST_NAME = "value"
Второе - имена для констант "Сообщение1" и "Сообщение2" - это антипаттерн. А когда сообщений в программе станет 10?) Имена у всего должны быть осознанными (пока не пишем на Go)
Третье - тут не нужно два похожих сообщения

2020-05-19 21:38 UTC, lugingf commented on compare_age.php
> +function enterUserAge() {
Функция - это действие, которое выполняет программа. В данном случае программа ничего не вводит. Она получает. Для таких функций хороший паттерн getUserAge()
(пока не пишем на Го - там принято будет просто userAge(), но то потом)

2020-05-19 21:38 UTC, lugingf commented on compare_age.php
> +        elseif ($message != MESSAGE2)
Я понял задумку переспросить. Это в общем норм. Но обычно на практике, если ввод со стороны пользователя невалидный, на бекенде мы выводим сообщение об ошибке и завершаем скрипт. Давай придерживаться такого сценария.

2020-05-20 05:50 UTC, gsa038 commented on compare_age.php
> +    define("MESSAGE1",  "Enter your age:");
Через const я так понял только в классе можно определять, через define вне класса, уберу их пока тогда совсем

2020-05-20 05:51 UTC, gsa038 commented on compare_age.php
> +    while (true) {
+

2020-05-20 05:52 UTC, gsa038 commented on compare_age.php
> +function enterUserAge() {
+

2020-05-20 05:53 UTC, gsa038 commented on compare_age.php
> +        elseif ($message != MESSAGE2)
+

2020-05-20 05:53 UTC, gsa038 commented
Все поправил

2020-05-20 07:10 UTC, lugingf requested changes
В остальном ок

2020-05-20 07:10 UTC, lugingf commented on compare_age.php
> +    else
Еще по стилю. Давай в php всегда обрамлять конструкции if фигурными скобками. Даже если в теле только одна строчка - все равно будем обрамлять

2020-05-20 07:10 UTC, lugingf commented on compare_age.php
> +    else
Тут else не нужен, совсем :) И вообще часто если есть возможность написать без else - лучше писать без него)
Тут если мы проваливаемся в if - мы выполняем return и выходим из функции. То что под else можно просто написать ниже, без самого else

2020-05-20 07:10 UTC, lugingf commented on compare_age.php
> +        return (int) $userAgeString;
О! Точно, давай сразу строгую типизацию использовать.
Везде декларируем declare(strict_types) = 1 и в сигнатурах функций пишем типы принимаемых и возвращаемых значений

2020-05-20 07:33 UTC, gsa038 commented on compare_age.php
> +    else
+

2020-05-20 07:34 UTC, gsa038 commented on compare_age.php
> +    else
+

2020-05-20 07:47 UTC, gsa038 commented on compare_age.php
> +        return (int) $userAgeString;
declare(strict_types=1);
+

2020-05-20 07:53 UTC, gsa038 commented
Проверяй)

2020-05-20 08:08 UTC, lugingf approved these changes
Норм)

2020-05-20 08:14 UTC, merged