Task 1 6 sequence stderr
gsa038/hello-php pull request #7
Opened 2020-05-20 11:42 UTC by gsa038

К программе из ветки TASK-1-5_~ добавить проверку, что все, что вводит пользователь, является
целым числом. В случае ошибки программа должна сообщать, какой именно
аргумент плохой (выводить его значение) и завершаться без дальнейших
вычислений. Вывод информации об ошибке должен происходить в стандартный
поток ошибок (STDERR)

P.S. Программа из ветки TASK-1-5_~
Написать программу, принимающую в качестве аргументов произвольную
последовательность целых чисел и выводящую эти числа:
в обратном порядке
в порядке возрастания
в порядке убывания
Добавить вывод доли (в %) каждого числа от суммы всех
введенных чисел. Дробные числа округлять до 2 знаков после запятой

2020-05-20 14:58 UTC, lugingf requested changes
Давай 4 и 5 ПРы закроем, сразу в этом будем работать

2020-05-20 14:58 UTC, lugingf commented on numbers_sequence.php
> +        elseif (is_float($value + 0)){
давай заменим эти elseif на просто if

2020-05-20 14:58 UTC, lugingf commented on numbers_sequence.php
> +echo "Choose an action:\n
Давай без выбора действий и перезапроса у пользователя) Там дальше будем тренироваться с аргументами 
Сейчас давай выводить все что есть

2020-05-20 14:58 UTC, lugingf commented on numbers_sequence.php
> +$numSeqPercent = array_sum($numSeq) / 100;
Этот блок просится в функцию)

2020-05-20 14:58 UTC, lugingf commented on numbers_sequence.php
> +    echo "Enter a sequence of numbers in format: 1,2,3..etc.:\n";
Предлагаю завести функцию, например, getUserInput(string $text) и переиспользовать ее дальше в заданиях

2020-05-20 14:58 UTC, lugingf commented on numbers_sequence.php
> +        elseif (is_float($value + 0)){
А что за маневр с "$value + 0" ? Зачем это?

2020-05-20 14:58 UTC, lugingf commented on numbers_sequence.php
> +    return array_map('intval', $numSeqArray);
по сути мы тут еще раз проходим по массиву, по которому проходили только что. Да, понятно, что тут мы на C++ проходим, что быстрей, но все таки. Если у нас цифр будет миллион, то это лишнее процессорное время :)

2020-05-20 14:58 UTC, lugingf commented on numbers_sequence.php
> +function getNumsFromConsole(): array {
Еще, PHP, в отличии от Python, например, позволяет функции унести вниз, а основное тело скрипта оставить вверху. Давай так и делать. Это потом облегчает чтение кода

2020-05-20 19:22 UTC, gsa038 commented
4 и 5 отличаются, т.к. постановка задачи не совсем точная и в последующих заданиях меняется результат. Закрываю?

2020-05-20 19:29 UTC, gsa038 commented on numbers_sequence.php
> +        elseif (is_float($value + 0)){
+

2020-05-20 19:43 UTC, gsa038 commented on numbers_sequence.php
> +    return array_map('intval', $numSeqArray);
+

2020-05-20 19:44 UTC, gsa038 commented on numbers_sequence.php
> +        elseif (is_float($value + 0)){
А как можно?)

2020-05-20 19:45 UTC, gsa038 commented on numbers_sequence.php
> +$numSeqPercent = array_sum($numSeq) / 100;
Я там уже это все переделал, уже в функции)

2020-05-20 19:46 UTC, gsa038 commented
Я там уже с аргументами начал, может сразу его смотреть будем?)

2020-05-20 19:47 UTC, gsa038 commented
Только еще немного не доделал(

2020-05-20 19:48 UTC, gsa038 commented on numbers_sequence.php
> +echo "Choose an action:\n
Я там уже переделываю под аргументы, поэтому там все равно switch будет)

2020-05-20 19:53 UTC, gsa038 commented on numbers_sequence.php
> +function getNumsFromConsole(): array {
+

2020-05-20 19:59 UTC, gsa038 commented on numbers_sequence.php
> +    echo "Enter a sequence of numbers in format: 1,2,3..etc.:\n";
+

2020-05-20 20:07 UTC, lugingf commented
> 4 и 5 отличаются, т.к. постановка задачи не совсем точная и в последующих заданиях меняется результат. Закрываю?

Да, закрывай

2020-05-20 20:08 UTC, lugingf commented
> Я там уже с аргументами начал, может сразу его смотреть будем?)

не, раз я сюда успел зайти, давай тут сначала)

2020-05-20 20:22 UTC, gsa038 commented
Тогда щас еще разок по твоим комментам все поправлю)

2020-05-20 20:22 UTC, gsa038 commented on numbers_sequence.php
> +        elseif (is_float($value + 0)){
+

2020-05-20 20:22 UTC, gsa038 commented on numbers_sequence.php
> +    echo "Enter a sequence of numbers in format: 1,2,3..etc.:\n";
+

2020-05-20 20:22 UTC, gsa038 commented on numbers_sequence.php
> +        elseif (is_float($value + 0)){
Сделал иначе

2020-05-20 20:23 UTC, gsa038 commented on numbers_sequence.php
> +    return array_map('intval', $numSeqArray);
+

2020-05-20 20:23 UTC, gsa038 commented on numbers_sequence.php
> +function getNumsFromConsole(): array {
+

2020-05-20 20:44 UTC, gsa038 commented on numbers_sequence.php
> +echo "Choose an action:\n
+

2020-05-20 20:45 UTC, gsa038 commented
Проверяй)

2020-05-20 20:55 UTC, lugingf requested changes
мяч!

2020-05-20 20:55 UTC, lugingf commented on numbers_sequence.php
> +echo "persents\n";
percents)

2020-05-20 20:55 UTC, lugingf commented on numbers_sequence.php
> +        if (is_float($value != (string)(int)$value)){
о господибожемой))) Ладно, давай так оставим. Я просто не помню как лучше проверить) Но в боевом коде так никогда не делай, ладно?))

2020-05-20 20:55 UTC, lugingf commented on numbers_sequence.php
> +    $numSeqString = getUserInput("Enter a sequence of numbers in format: 1,2,3..etc.:");
Еще неплохо избегать сокращений в названиях и именах

2020-05-20 20:55 UTC, lugingf commented on numbers_sequence.php
> +function printNumsPercentArray(&$array):void {
Давай так не делать. Функция должна выполнять что-то одно. Тут написано, что она что-то выводит на печать, но она под капотом что-то еще и вычисляет.
Еще давай стараться избегать передачи аргументов по ссылке, если на это нет явной необходимости. Это удобная штука, но она немного... неявная. И немного ухудшает читабельность.
Получи лучше здесь просто ассоциативный массив с посчитанными занчениями, а потом его выведи на печать, отдельно

2020-05-20 21:18 UTC, gsa038 commented on numbers_sequence.php
> +        if (is_float($value != (string)(int)$value)){
) я с ходу не нашел. На php.net нет ничего другого)

2020-05-20 21:19 UTC, gsa038 commented on numbers_sequence.php
> +    $numSeqString = getUserInput("Enter a sequence of numbers in format: 1,2,3..etc.:");
+

2020-05-20 21:19 UTC, gsa038 commented on numbers_sequence.php
> +echo "persents\n";
очепятка +

2020-05-20 21:29 UTC, gsa038 commented on numbers_sequence.php
> +function printNumsPercentArray(&$array):void {
+

2020-05-20 21:29 UTC, gsa038 commented
Проверяй)

2020-05-21 16:07 UTC, lugingf approved these changes
Ок

2020-05-21 18:34 UTC, merged