Task 1 7 argv
gsa038/hello-php pull request #8
Opened 2020-05-21 07:20 UTC by gsa038

К программе из ветки TASK-1-6 добавить возможность управлять выводом с помощью опций:
1. -p - если задана эта опция, выводить доли из п. 5, иначе - только числа
2. --order=<reverse|asc|desc> - если задана такая опция, выводить числа
соответственно как в 4a, 4b, 4c. Если не задана, выводить в исходном
порядке.

P.S. Программа из ветки TASK-1-6_~
Написать программу, принимающую в качестве аргументов произвольную
последовательность целых чисел и выводящую эти числа:
в обратном порядке
в порядке возрастания
в порядке убывания

Добавить вывод доли (в %) каждого числа от суммы всех
введенных чисел. Дробные числа округлять до 2 знаков после запятой

Добавить проверку, что все, что вводит пользователь, является
целым числом. В случае ошибки программа должна сообщать, какой именно
аргумент плохой (выводить его значение) и завершаться без дальнейших
вычислений. Вывод информации об ошибке должен происходить в стандартный
поток ошибок (STDERR)

2020-05-21 17:19 UTC, lugingf requested changes
Давай посмотрим на функцию getopt()

2020-05-21 17:19 UTC, lugingf commented on numbers_sequence.php
> +        switch ($argv[$i]) {
Хитро, но, получается, мы можем одну опцию задать несколько раз и она отработает?)

2020-05-21 17:19 UTC, lugingf commented on numbers_sequence.php
> +function printKeyReverseSortedArray(array $array):void {
Давай все таки стараться отделять слой логики с преобразованием данных и слой логики с выводом данных. Сегодня нам в программе нужно вывести данные на печать в консоль. А завтра потребуется отправить по HTTP или записать в базу

2020-05-21 18:17 UTC, gsa038 commented on numbers_sequence.php
> +        switch ($argv[$i]) {
Это плохо?)

2020-05-21 18:34 UTC, gsa038 commented on numbers_sequence.php
> +function printKeyReverseSortedArray(array $array):void {
Все убрал в switch

2020-05-21 19:20 UTC, gsa038 commented
Дичь с getopt замутил, тебе явно не понравится)))

2020-05-21 19:47 UTC, gsa038 commented
`function doOrderAndPrint(string $orderParam, array $array):void {`
Так ты тоже говорил вроде не делать, но пришлось(

2020-05-22 18:06 UTC, lugingf commented on numbers_sequence.php
> +        switch ($argv[$i]) {
ну обычно утилиты так себя не ведут

2020-05-25 16:08 UTC, lugingf requested changes

2020-05-25 16:08 UTC, lugingf commented on numbers_sequence.php
> +    foreach ($options as $opt => $value) {
Ты когда линуксовые утилиты используешь - они обычно дают возможность две опции задать и обе отработать?

2020-05-25 16:08 UTC, lugingf commented on numbers_sequence.php
> +        echo "$value ";
В php есть implode()

2020-05-25 16:08 UTC, lugingf commented on numbers_sequence.php
> +                echo "Unknown argument\n";
Вообще хорошей практикой считается отдать какой-нибудь хэлп для утилиты, если что-то передано неверно.

2020-05-26 06:06 UTC, gsa038 commented on numbers_sequence.php
> +    foreach ($options as $opt => $value) {
Да, конечно, может хоть сразу десяток разных параметров использоваться. Не видел чтобы один и тот же параметр использовали сразу несколько раз, но это был мой личный эксперимент на твой суд)

2020-05-26 06:19 UTC, gsa038 commented on numbers_sequence.php
> +        echo "$value ";
+

2020-05-26 06:19 UTC, gsa038 commented on numbers_sequence.php
> +                echo "Unknown argument\n";
+

2020-05-26 08:18 UTC, gsa038 commented on numbers_sequence.php
> +    foreach ($options as $opt => $value) {
Добавил проверку, сделал каждый аргумент один раз

2020-05-27 10:53 UTC, lugingf approved these changes

2020-05-27 13:56 UTC, merged