for check task 1-8
gsa038/hello-php pull request #9
Opened 2020-05-21 08:42 UTC by gsa038

Написать программу, принимающую на вход последовательность аргументов.
Программа должна вывести 5 наиболее часто встречающихся аргументов (или
меньше, если было введено менее 5 различных аргументов) и кол-ва повторений
для них.

2020-05-22 18:04 UTC, lugingf requested changes

2020-05-22 18:04 UTC, lugingf commented on argv_frequency.php
> +    if (!($echoCounter < 5)) {
у нас есть `array_slice()`

2020-05-22 19:00 UTC, gsa038 commented on argv_frequency.php
> +    if (!($echoCounter < 5)) {
+

2020-05-25 16:10 UTC, lugingf requested changes

2020-05-25 16:10 UTC, lugingf commented on argv_frequency.php
> +foreach (array_slice($counters, 0, 5, true) as $argKey => $argKeyCount) {
Давай стараться как можно меньше лишних вложенностей. Это правда мешает чтению :)

2020-05-26 05:30 UTC, gsa038 commented on argv_frequency.php
> +foreach (array_slice($counters, 0, 5, true) as $argKey => $argKeyCount) {
Поправил, сразу вопрос, упрощаем всегда насколько это возможно?

2020-05-27 10:55 UTC, lugingf approved these changes

2020-05-27 13:58 UTC, merged